### ISSUE TITLE
next 主题无法离线部分 lib 资源

### ISSUE THREAD

**Issue by ywzhaiqi** [JLHwung/hexo-offline#37]
由于 next 主题采用  `jquery.fancybox.css?v=2.1.5` 这样的链接形式，多了 `?v=2.1.5`，造成这种类型的资源无法离线。

查看了 [sw-precache](https://github.com/GoogleChromeLabs/sw-precache#ignoreurlparametersmatching-arrayregex) 文档，发现只要添加 `ignoreUrlParametersMatching` 即可。

一番尝试后，只需在 `_config.yml` 中添加如下部分即可正常离线。

```yaml
offline:
  # next 主题部分资源以 ?v=2.1.5 引入，此配置用于此配置用于让这类资源生效
  ignoreUrlParametersMatching:
  - /^v$/
```

希望作者能添加到文档中。
