### ISSUE TITLE
How can I use navigateFallback in this library?

### ISSUE THREAD

**Issue by cubesky** [JLHwung/hexo-offline#40]
I want to return an offline page instead of system offline page. It seems I need `navigateFallback`, how can I set this

**Comment by JLHwung** [comment]
As documented [here](https://github.com/GoogleChromeLabs/sw-precache#navigatefallback-string), `navigateFallback` is a string, so you can set this option in your hexo root config.

```yml
offline:
  staticFileGlobs: ['/shell.html']
  navigateFallback: '/shell.html'
```
