### ISSUE TITLE
ignore some file

### ISSUE THREAD

**Issue by edeity** [JLHwung/hexo-offline#41]
There's something that I dont want offline;
I find the [issuse](https://github.com/GoogleChromeLabs/sw-precache/issues/97) here

but config like this wont work

```
staticFileGlobs: 
- !no-offline/**/*
```

other regex try `!/no-offline/**/*`、`/!(no-offline)/**/*`....

How can I config to ignore some file?

**Comment by JLHwung** [comment]
The `sw-precache` uses [glob](https://github.com/isaacs/node-glob) to select files, which uses [minimatch](https://www.npmjs.com/package/minimatch) to match the files.

Let's say if you want to match everything except `/no-offline/**/*.ext`, you can use `/!(no-offline)/**/*.ext`. One can show that
```js
var minimatch = require("minimatch")

var glob = "/!(no-offline)/**/*.json";
minimatch("/offline/file.json", glob)
// returns true

minimatch("/no-offline/file.json", glob)
// returns false
```
You can try out `minimatch` [here](https://runkit.com/npm/minimatch) to work on your globs.

**Comment by edeity** [comment]
still no working

following is my `__config.yml` config

```
# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs: /!(app)/**/*.png
  verbose: true

# service_worker:
offline:
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.bootcss.com
```

I try dozens writing types， but the `service-worker.js` still containers some url look like this

```javascript
var precacheConfig = [
...
["/app/brief/img/hb.png","d164ec0e535f066cda2773fc9b22536c"],
["/app/brief/img/patch.png","d301e2029cb9f8bb015cd3d0d07995f1"],
["/app/brief/img/product/balaccount.png","2b5996f25e23c717f9a304f3d8b7c079"]
...
]
```

I dont know where is wrong, how can i write the `staticFileGlobs` so I can ignore ths `*. png` in `app`;

3ks

**Comment by JLHwung** [comment]
@edeity Hi
Have you tried the following settings?
```
offline:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs: /!(app)/**/*.png
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.bootcss.com
```
`hexo-offline` will only parse the configuration in `offline` section, the `service_worker` section is rendered useless.

**Comment by Ryan-Miao** [comment]
But I found the offline only to find the `service_worker` section instead of `offline`, it will throw an exception when I use `offline`

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: EPERM: operation not permitted, scandir 'D:\$RECYCLE.BIN\S-1-5-18'
    at Object.fs.readdirSync (fs.js:904:18)
    at GlobSync._readdir (D:\workspace\blog\next\node_modules\glob\sync.js:288:41)
    at GlobSync._readdirInGlobStar (D:\workspace\blog\next\node_modules\glob\sync.js:267:20)
    at GlobSync._readdir (D:\workspace\blog\next\node_modules\glob\sync.js:276:17)
    at GlobSync._processReaddir (D:\workspace\blog\next\node_modules\glob\sync.js:137:22)
    at GlobSync._process (D:\workspace\blog\next\node_modules\glob\sync.js:132:10)
    at GlobSync._processGlobStar (D:\workspace\blog\next\node_modules\glob\sync.js:380:10)
    at GlobSync._process (D:\workspace\blog\next\node_modules\glob\sync.js:130:10)
    at GlobSync._processGlobStar (D:\workspace\blog\next\node_modules\glob\sync.js:383:10)
    at GlobSync._process (D:\workspace\blog\next\node_modules\glob\sync.js:130:10)
    at new GlobSync (D:\workspace\blog\next\node_modules\glob\sync.js:48:10)
    at Function.globSync [as sync] (D:\workspace\blog\next\node_modules\glob\sync.js:26:10)
    at getFilesAndSizesAndHashesForGlobPattern (D:\workspace\blog\next\node_modules\sw-precache\lib\sw-precache.js:55:15)
    at D:\workspace\blog\next\node_modules\sw-precache\lib\sw-precache.js:161:36
    at Array.forEach (<anonymous>)
    at D:\workspace\blog\next\node_modules\sw-precache\lib\sw-precache.js:160:28
    at new Promise (<anonymous>)
    at generate (D:\workspace\blog\next\node_modules\sw-precache\lib\sw-precache.js:128:10)
    at D:\workspace\blog\next\node_modules\sw-precache\lib\sw-precache.js:346:5
    at new Promise (<anonymous>)
    at Object.write (D:\workspace\blog\next\node_modules\sw-precache\lib\sw-precache.js:326:10)
    at Hexo.runSWPrecache (D:\workspace\blog\next\node_modules\hexo-offline\lib\lib\run-sw-precache.js:54:31)

```


It will be work if use the following config:

```
# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - /**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  - /lib/**/*.js
  - /lib/**/*.css
  - /images/*
  - /js/src/**/*.js
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.bootcss.com

```
