### ISSUE TITLE
没有编译到Public中

### ISSUE THREAD

**Issue by chy9002** [JLHwung/hexo-offline#45]
按照说明安装后如下配置：
```
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
  ignoreUrlParametersMatching:
  - /^v$/
```
然后`hexo clean && hexo g`后，并没有看到sw的注册的相关脚本在public文件中出现。
